# Something Understood 

*Something Understood* broadcast weekly from 1995 for 24 years [@Chisholm2019] before new production was cut by the BBC, although they kept the series running on repeats. At 50 episodes a year, that might make for a catalogue of up to 1,200 programmes but only `r nrow(df_su)` have been identified so far [@BBC-genome-su; @BBCR4-su-website; @LOFTUS2007].

## Acquiring a list of episodes

A [list of episodes](#su-episode-list) of *Something Understood* was obtained from the BBC's *Something Understood* website [@BBCR4-su-website]. A database was constructed using a simple `csv` (comma-separated variable) text-based format which includes episode information and the BBC's unique programme identifier or `PID`. `r sum(df_su$PID!="")` episodes broadcast since February 2007 are listed and have their own page and `PID`. A column `Plink` is derived in the dataset to provide a hyperlink to these programme websites. Links to BBC archive pages for episodes broadcast between 2 October 2005 and 29 March 2009 [@BBC-archive-su] are generated and displayed with (*alt.*). Data captured from these pages is in the `Archive-details` column: it comprises more running order than a description of the programme.

Earlier programmes were located in the BBC's Genome project site [@BBC-genome-su] and @LOFTUS2007.