# Episodes {-}

```{r df-SU, include = FALSE} 
df_su <- read.csv("su.csv")
```

*Something Understood* broadcast weekly from 1995 for 24 years [@Chisholm2019] before new production was cut by the BBC. They kept the series running on repeats until Easter 2024 when it was apparently quietly removed[^end] from the schedule. At 50 episodes a year, that might make for a catalogue of up to 1,200 programmes but I have only identified `r nrow(df_su)` so far [@BBCb; @BBCR4-su-website; @LOFTUS2007].

[^end]: It is possibly significant that the last episode broadcast was a repeat of the last original episode made, with Sir Mark Tully himself "striking a valedictory note" with [*In My End Is My Beginning*](https://www.bbc.co.uk/programmes/m0004dwy).

## Acquiring a list of episodes

A [list of episodes](#su-episode-list) of *Something Understood* was obtained from the BBC's *Something Understood* website [@BBCR4-su-website]. A database was constructed using a simple `csv` (comma-separated variable) text-based format which includes episode information and the BBC's unique programme identifier[^pid-note] or `PID`. `r sum(df_su$PID!="")` episodes broadcast since February 2007 are listed and have their own page and `PID`. A column is derived in the dataset to provide a hyperlink to these programme websites. Links to BBC archive pages for episodes broadcast between 2 October 2005 and 29 March 2009 [@BBC] are generated and displayed with (*alt.*). Data captured from these pages is in the `Archive-details` column: it comprises more running order than a description of the programme.

[^pid-note]: With the at least one of the repeats being aired in 2023-4, I noticed (in December 2023) that a new PID has been allocated, for which I have created a duplication in the database. I have kept these distinct for now, because in these cases, the BBC are maintaining separate episode pages, for example, *Stories of the Nativity* has [b00wnrw8](https://www.bbc.co.uk/programmes/b00wnrw8) and [m001v7kd](https://www.bbc.co.uk/programmes/m001v7kd). These are the same episode, as far as I can tell.

Earlier programmes were located in the BBC's Genome project site [@BBCb] and @LOFTUS2007.

## Cataloguing and describing episodes

Broadcast and production information, along with episode descriptions has been obtained between July and October 2021 for all of the `r sum(df_su$PID!="")` known episodes on the BBC Programme website [@BBCR4-su-website]. This process of cataloguing includes cleaning of the data on import escaping text where appropriate. This information has been cross-checked with the BBC's Genome Project [@BBCb] and the *Something Understood* Archive pages [@BBC]. `r nrow(df_su)` episodes have been identified so far but the exercise is not yet complete (and may never be, I am doing other things at present).

It is possible that there are discrepancies between the production company records and the BBC's index [@BBCb] but the latter is scraped from OCR[^tla-ocr]'d paper copies of *The Radio Times* with crowd-sourced corrections and additions, as well as more recent programme schedule information. Some manual correction of OCR scanning errors is required, mostly to spelling of names or obvious errors like "I caught a Rsh". 

[^tla-ocr]: OCR = optical character recognition scans

## Tasks still to do

Completing the cataloguing of *Something Understood* has had to take a place on a "back burner" while I focus on my [main research](https://sptr.net/research.html), but I may have time after that. Please let me know if you want to help!

* [ ] Complete mining of the [BBC Genome Project](https://genome.ch.bbc.co.uk/search/20/20?order=first&q=Something+Understood&after=1995-01-01T00%3A00%3A00.000Z#top) for data on Something Understood (1997 ff.).
* [ ] Mine the [BBC Something Understood Archive site](https://www.bbc.co.uk/radio4/religion/somethingunderstood_archive.shtml)
