# Themes and key terms {-}

::: {.grid}

::: {.g-col-4}

Using the programme descriptions as a corpus, the most frequently occurring words may be plotted as a "word cloud". Draw your own conclusions.
:::
::: {.g-col-8}

```{r df-SU, include = FALSE} 
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")

df_su <- read.csv("su.csv")

# Create a corpus
sucorpus <- Corpus(VectorSource(df_su$Description))

# Preprocess the text
sucorpus <- tm_map(sucorpus, content_transformer(tolower))
sucorpus <- tm_map(sucorpus, removePunctuation)
sucorpus <- tm_map(sucorpus, removeNumbers)
sucorpus <- tm_map(sucorpus, removeWords, stopwords("en"))
sucorpus <- tm_map(sucorpus, removeWords, c("can", "readers", "programme", "br"))
sucorpus <- tm_map(sucorpus, stripWhitespace)

# Create a Document-Term Matrix
dtm <- TermDocumentMatrix(sucorpus)
m <- as.matrix(dtm)
v <- sort(rowSums(m), decreasing = TRUE)
d <- data.frame(word = names(v), freq = v)
```
```{r echo=FALSE, warning=FALSE}
# Plot the word cloud
wordcloud(words = d$word, rot.per=.45, freq = d$freq, min.freq = 24, random.order = FALSE, colors = brewer.pal(8, "Dark2"))
```
:::
:::
